; ===========================================================================
; File: test_assignment_parens.lgd
; Generated by LGD Decompiler V_0.2.0
; Bytecode Start: 0x9F3
; Format: [File Offset] [Hex Dump]           [Mnemonic]     [Operands]     [Comments]
; ===========================================================================

;Function Action() Begin
  09F3:  01 01 00 00 00     PUSH_INT     1
  09F8:  1F                 RET          
  09F9:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  09FE:  1F                 RET                              ; mark end of function
;Function Action() End
; ------------------------------------------------------------

;Function stringCommand() Begin
  09FF:  01 00 00 00 00     PUSH_INT     0
  0A04:  1F                 RET          
  0A05:  19 0D 00 00 00     LINE_NUM     13                  ; Code Line 13
  0A0A:  1F                 RET                              ; mark end of function
;Function stringCommand() End
; ------------------------------------------------------------

;Function GetValue() Begin
  0A0B:  01 2A 00 00 00     PUSH_INT     42
  0A10:  1F                 RET          
  0A11:  19 12 00 00 00     LINE_NUM     18                  ; Code Line 18
  0A16:  1F                 RET                              ; mark end of function
;Function GetValue() End
; ------------------------------------------------------------

;Function GetMapName() Begin
  0A17:  02 6D 61 70 73 5C  PUSH_STR     "maps\survive_01.map"
        73 75 72 76 69 76
        65 5F 30 31 2E 6D
        61 70 00
  0A2C:  1F                 RET          
  0A2D:  19 17 00 00 00     LINE_NUM     23                  ; Code Line 23
  0A32:  1F                 RET                              ; mark end of function
;Function GetMapName() End
; ------------------------------------------------------------

;Function test_advanced_assignments() Begin
  0A33:  19 20 00 00 00     LINE_NUM     32                  ; Code Line 32
  0A38:  19 21 00 00 00     LINE_NUM     33                  ; Code Line 33
  0A3D:  19 22 00 00 00     LINE_NUM     34                  ; Code Line 34
  0A42:  19 23 00 00 00     LINE_NUM     35                  ; Code Line 35
  0A47:  19 24 00 00 00     LINE_NUM     36                  ; Code Line 36
  0A4C:  19 25 00 00 00     LINE_NUM     37                  ; Code Line 37
  0A51:  01 64 00 00 00     PUSH_INT     100
  0A56:  26 05 00 00 00     ASSIGN       test_advanced_assignments_local0
  0A5B:  19 2A 00 00 00     LINE_NUM     42                  ; Code Line 42
  0A60:  24 05 00 00 00     PUSH_VAR     test_advanced_assignments_local0
  0A65:  27 06 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local1, +=
  0A6B:  19 2B 00 00 00     LINE_NUM     43                  ; Code Line 43
  0A70:  24 06 00 00 00     PUSH_VAR     test_advanced_assignments_local1
  0A75:  27 07 00 00 00 09  OP_ASSIGN    test_advanced_assignments_local2, -=
  0A7B:  19 2C 00 00 00     LINE_NUM     44                  ; Code Line 44
  0A80:  01 00 00 00 00     PUSH_INT     0
  0A85:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0A8A:  26 06 00 00 00     ASSIGN       test_advanced_assignments_local1
  0A8F:  26 05 00 00 00     ASSIGN       test_advanced_assignments_local0
  0A94:  19 2F 00 00 00     LINE_NUM     47                  ; Code Line 47
  0A99:  01 00 00 00 00     PUSH_INT     0
  0A9E:  26 05 00 00 00     ASSIGN       test_advanced_assignments_local0
  0AA3:  19 32 00 00 00     LINE_NUM     50                  ; Code Line 50
loc_0AA8:
  0AA8:  24 05 00 00 00     PUSH_VAR     test_advanced_assignments_local0
  0AAD:  01 14 00 00 00     PUSH_INT     20
  0AB2:  10                 LT           
  0AB3:  18 38 00 00 00     JMP_FALSE    loc_0AEC            ; Rel: +0x38
  0AB8:  1C 19 00 00 00     JMP          loc_0AD2            ; Rel: +0x19
loc_0ABD:
  0ABD:  01 01 00 00 00     PUSH_INT     1
  0AC2:  27 05 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local0, +=
  0AC8:  19 32 00 00 00     LINE_NUM     50                  ; Code Line 50
  0ACD:  1C DA FF FF FF     JMP          loc_0AA8            ; Rel: 0x-26
loc_0AD2:
  0AD2:  01 00 00 00 00     PUSH_INT     0
  0AD7:  24 05 00 00 00     PUSH_VAR     test_advanced_assignments_local0
  0ADC:  28                 ARRAY_IDX    
  0ADD:  26 08 00 00 00     ASSIGN       test_advanced_assignments_local3
  0AE2:  19 33 00 00 00     LINE_NUM     51                  ; Code Line 51
  0AE7:  1C D5 FF FF FF     JMP          loc_0ABD            ; Rel: 0x-2B
loc_0AEC:
  0AEC:  01 00 00 00 00     PUSH_INT     0
  0AF1:  26 00 00 00 00     ASSIGN       Action_arg0
  0AF6:  1A                 ARG_COMMIT   
  0AF7:  01 05 00 00 00     PUSH_INT     5
  0AFC:  26 05 00 00 00     ASSIGN       test_advanced_assignments_local0
  0B01:  26 01 00 00 00     ASSIGN       Action_arg1
  0B06:  1A                 ARG_COMMIT   
  0B07:  01 0A 00 00 00     PUSH_INT     10
  0B0C:  27 06 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local1, +=
  0B12:  26 02 00 00 00     ASSIGN       Action_arg2
  0B17:  1A                 ARG_COMMIT   
  0B18:  1E 00 00 00 00     CALL_FUNC    Action
  0B1D:  19 3D 00 00 00     LINE_NUM     61                  ; Code Line 61
  0B22:  02 41 6C 65 72 74  PUSH_STR     "Alert"
        00
  0B29:  26 1C 00 00 00     ASSIGN       test_advanced_assignments_local23
  0B2E:  26 03 00 00 00     ASSIGN       stringCommand_arg0
  0B33:  1A                 ARG_COMMIT   
  0B34:  02 44 61 6E 67 65  PUSH_STR     "Danger"
        72 00
  0B3C:  26 1D 00 00 00     ASSIGN       test_advanced_assignments_local24
  0B41:  26 04 00 00 00     ASSIGN       stringCommand_arg1
  0B46:  1A                 ARG_COMMIT   
  0B47:  1E 01 00 00 00     CALL_FUNC    stringCommand
  0B4C:  19 40 00 00 00     LINE_NUM     64                  ; Code Line 64
loc_0B51:
  0B51:  01 01 00 00 00     PUSH_INT     1
  0B56:  27 05 00 00 00 09  OP_ASSIGN    test_advanced_assignments_local0, -=
  0B5C:  01 00 00 00 00     PUSH_INT     0
  0B61:  11                 GE           
  0B62:  18 19 00 00 00     JMP_FALSE    loc_0B7C            ; Rel: +0x19
  0B67:  01 01 00 00 00     PUSH_INT     1
  0B6C:  27 06 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local1, +=
  0B72:  19 4A 00 00 00     LINE_NUM     74                  ; Code Line 74
  0B77:  1C D9 FF FF FF     JMP          loc_0B51            ; Rel: 0x-27
loc_0B7C:
  0B7C:  1E 02 00 00 00     CALL_FUNC    GetValue
  0B81:  26 05 00 00 00     ASSIGN       test_advanced_assignments_local0
  0B86:  01 00 00 00 00     PUSH_INT     0
  0B8B:  14                 NE           
  0B8C:  2C 16 00 00 00     AND_JMP      loc_0BA3            ; Rel: +0x16
  0B91:  24 05 00 00 00     PUSH_VAR     test_advanced_assignments_local0
  0B96:  27 06 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local1, +=
  0B9C:  01 0A 00 00 00     PUSH_INT     10
  0BA1:  0F                 GT           
  0BA2:  15                 LOG_AND      
loc_0BA3:
  0BA3:  18 13 00 00 00     JMP_FALSE    loc_0BB7            ; Rel: +0x13
  0BA8:  01 01 00 00 00     PUSH_INT     1
  0BAD:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0BB2:  19 50 00 00 00     LINE_NUM     80                  ; Code Line 80
loc_0BB7:
  0BB7:  1E 03 00 00 00     CALL_FUNC    GetMapName
  0BBC:  26 1C 00 00 00     ASSIGN       test_advanced_assignments_local23
  0BC1:  02 6D 61 70 73 5C  PUSH_STR     "maps\survive_01.map"
        73 75 72 76 69 76
        65 5F 30 31 2E 6D
        61 70 00
  0BD6:  0D                 EQ           
  0BD7:  18 13 00 00 00     JMP_FALSE    loc_0BEB            ; Rel: +0x13
  0BDC:  01 64 00 00 00     PUSH_INT     100
  0BE1:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0BE6:  19 55 00 00 00     LINE_NUM     85                  ; Code Line 85
loc_0BEB:
  0BEB:  01 05 00 00 00     PUSH_INT     5
  0BF0:  27 06 00 00 00 09  OP_ASSIGN    test_advanced_assignments_local1, -=
  0BF6:  01 01 00 00 00     PUSH_INT     1
  0BFB:  27 05 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local0, +=
  0C01:  28                 ARRAY_IDX    
  0C02:  26 08 00 00 00     ASSIGN       test_advanced_assignments_local3
  0C07:  19 5F 00 00 00     LINE_NUM     95                  ; Code Line 95
  0C0C:  01 01 00 00 00     PUSH_INT     1
  0C11:  26 05 00 00 00     ASSIGN       test_advanced_assignments_local0
  0C16:  01 02 00 00 00     PUSH_INT     2
  0C1B:  17                 SHL          
  0C1C:  01 02 00 00 00     PUSH_INT     2
  0C21:  26 06 00 00 00     ASSIGN       test_advanced_assignments_local1
  0C26:  01 01 00 00 00     PUSH_INT     1
  0C2B:  16                 SHR          
  0C2C:  0C                 BIT_AND      
  0C2D:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0C32:  19 63 00 00 00     LINE_NUM     99                  ; Code Line 99
  0C37:  01 64 00 00 00     PUSH_INT     100
  0C3C:  01 0A 00 00 00     PUSH_INT     10
  0C41:  27 05 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local0, +=
  0C47:  01 05 00 00 00     PUSH_INT     5
  0C4C:  27 06 00 00 00 09  OP_ASSIGN    test_advanced_assignments_local1, -=
  0C52:  13                 MUL          
  0C53:  09                 SUB          
  0C54:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0C59:  19 67 00 00 00     LINE_NUM     103                 ; Code Line 103
  0C5E:  01 05 00 00 00     PUSH_INT     5
  0C63:  26 05 00 00 00     ASSIGN       test_advanced_assignments_local0
  0C68:  03                 NEG          
  0C69:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0C6E:  19 70 00 00 00     LINE_NUM     112                 ; Code Line 112
  0C73:  01 01 00 00 00     PUSH_INT     1
  0C78:  27 06 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local1, +=
  0C7E:  05                 LOG_NOT      
  0C7F:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0C84:  19 74 00 00 00     LINE_NUM     116                 ; Code Line 116
  0C89:  01 02 00 00 00     PUSH_INT     2
  0C8E:  27 05 00 00 00 09  OP_ASSIGN    test_advanced_assignments_local0, -=
  0C94:  04                 BIT_NOT      
  0C95:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0C9A:  19 78 00 00 00     LINE_NUM     120                 ; Code Line 120
  0C9F:  01 0A 00 00 00     PUSH_INT     10
  0CA4:  01 00 00 00 00     PUSH_INT     0
  0CA9:  28                 ARRAY_IDX    
  0CAA:  26 08 00 00 00     ASSIGN       test_advanced_assignments_local3
  0CAF:  27 06 00 00 00 09  OP_ASSIGN    test_advanced_assignments_local1, -=
  0CB5:  27 05 00 00 00 08  OP_ASSIGN    test_advanced_assignments_local0, +=
  0CBB:  26 07 00 00 00     ASSIGN       test_advanced_assignments_local2
  0CC0:  19 81 00 00 00     LINE_NUM     129                 ; Code Line 129
  0CC5:  1F                 RET                              ; mark end of function
;Function test_advanced_assignments() End
; ------------------------------------------------------------
