; ===========================================================================
; File: test_loc_unstatic_arr.lgd
; Generated by LGD Decompiler V_0.3.0
; Bytecode Start: 0xA76
; Format: [File Offset] [Hex Dump]           [Mnemonic]     [Operands]     [Comments]
; ===========================================================================

;Function main() Begin
  0A76:  01 64 00 00 00     PUSH_INT     100
  0A7B:  26 00 00 00 00     ASSIGN       main_local0
  0A80:  19 01 00 00 00     LINE_NUM     1                   ; Code Line 1
  0A85:  19 02 00 00 00     LINE_NUM     2                   ; Code Line 2
  0A8A:  19 03 00 00 00     LINE_NUM     3                   ; Code Line 3
  0A8F:  19 06 00 00 00     LINE_NUM     6                   ; Code Line 6
  0A94:  19 07 00 00 00     LINE_NUM     7                   ; Code Line 7
  0A99:  01 01 00 00 00     PUSH_INT     1
  0A9E:  26 10 00 00 00     ASSIGN       main_local16
  0AA3:  19 07 00 00 00     LINE_NUM     7                   ; Code Line 7
  0AA8:  01 02 00 00 00     PUSH_INT     2
  0AAD:  26 11 00 00 00     ASSIGN       main_local17
  0AB2:  19 07 00 00 00     LINE_NUM     7                   ; Code Line 7
  0AB7:  01 03 00 00 00     PUSH_INT     3
  0ABC:  26 12 00 00 00     ASSIGN       main_local18
  0AC1:  19 07 00 00 00     LINE_NUM     7                   ; Code Line 7
  0AC6:  01 04 00 00 00     PUSH_INT     4
  0ACB:  26 13 00 00 00     ASSIGN       main_local19
  0AD0:  19 07 00 00 00     LINE_NUM     7                   ; Code Line 7
  0AD5:  01 05 00 00 00     PUSH_INT     5
  0ADA:  26 14 00 00 00     ASSIGN       main_local20
  0ADF:  19 07 00 00 00     LINE_NUM     7                   ; Code Line 7
  0AE4:  01 06 00 00 00     PUSH_INT     6
  0AE9:  26 15 00 00 00     ASSIGN       main_local21
  0AEE:  19 07 00 00 00     LINE_NUM     7                   ; Code Line 7
  0AF3:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  0AF8:  01 01 00 00 00     PUSH_INT     1
  0AFD:  26 16 00 00 00     ASSIGN       main_local22
  0B02:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  0B07:  01 02 00 00 00     PUSH_INT     2
  0B0C:  26 17 00 00 00     ASSIGN       main_local23
  0B11:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  0B16:  01 03 00 00 00     PUSH_INT     3
  0B1B:  26 18 00 00 00     ASSIGN       main_local24
  0B20:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  0B25:  01 04 00 00 00     PUSH_INT     4
  0B2A:  26 19 00 00 00     ASSIGN       main_local25
  0B2F:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  0B34:  01 05 00 00 00     PUSH_INT     5
  0B39:  26 1A 00 00 00     ASSIGN       main_local26
  0B3E:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  0B43:  01 06 00 00 00     PUSH_INT     6
  0B48:  26 1B 00 00 00     ASSIGN       main_local27
  0B4D:  19 08 00 00 00     LINE_NUM     8                   ; Code Line 8
  0B52:  19 09 00 00 00     LINE_NUM     9                   ; Code Line 9
  0B57:  19 0C 00 00 00     LINE_NUM     12                  ; Code Line 12
  0B5C:  19 0D 00 00 00     LINE_NUM     13                  ; Code Line 13
  0B61:  02 31 31 31 00     PUSH_STR     "111"
  0B66:  26 2D 00 00 00     ASSIGN       main_local45
  0B6B:  19 0D 00 00 00     LINE_NUM     13                  ; Code Line 13
  0B70:  02 32 32 32 00     PUSH_STR     "222"
  0B75:  26 2E 00 00 00     ASSIGN       main_local46
  0B7A:  19 0D 00 00 00     LINE_NUM     13                  ; Code Line 13
  0B7F:  02 33 33 33 00     PUSH_STR     "333"
  0B84:  26 2F 00 00 00     ASSIGN       main_local47
  0B89:  19 0D 00 00 00     LINE_NUM     13                  ; Code Line 13
  0B8E:  19 0E 00 00 00     LINE_NUM     14                  ; Code Line 14
  0B93:  19 0F 00 00 00     LINE_NUM     15                  ; Code Line 15
  0B98:  01 32 00 00 00     PUSH_INT     50
  0B9D:  26 00 00 00 00     ASSIGN       main_local0
  0BA2:  19 11 00 00 00     LINE_NUM     17                  ; Code Line 17
  0BA7:  01 96 00 00 00     PUSH_INT     150
  0BAC:  26 01 00 00 00     ASSIGN       main_local1
  0BB1:  19 12 00 00 00     LINE_NUM     18                  ; Code Line 18
  0BB6:  01 64 00 00 00     PUSH_INT     100
  0BBB:  01 01 00 00 00     PUSH_INT     1
  0BC0:  28                 ARRAY_IDX    
  0BC1:  26 10 00 00 00     ASSIGN       main_local16
  0BC6:  19 14 00 00 00     LINE_NUM     20                  ; Code Line 20
  0BCB:  1F                 RET                              ; mark end of function
;Function main() End
; ------------------------------------------------------------
