; ===========================================================================
; File: test_stack_in_ifdef.lgd
; Generated by LGD Decompiler V_0.2.0
; Bytecode Start: 0x9DA
; Format: [File Offset] [Hex Dump]           [Mnemonic]     [Operands]     [Comments]
; ===========================================================================

;Function test_ifdef_bug_and_end() Begin
  09DA:  01 0A 00 00 00     PUSH_INT     10
  09DF:  26 00 00 00 00     ASSIGN       test_ifdef_bug_and_end_local0
  09E4:  19 11 00 00 00     LINE_NUM     17                  ; Code Line 17
  09E9:  19 12 00 00 00     LINE_NUM     18                  ; Code Line 18
  09EE:  24 00 00 00 00     PUSH_VAR     test_ifdef_bug_and_end_local0
  09F3:  01 64 00 00 00     PUSH_INT     100
  09F8:  0F                 GT           
  09F9:  2C 05 00 00 00     AND_JMP      loc_09FF            ; Rel: +0x5
  09FE:  15                 LOG_AND      
loc_09FF:
  09FF:  18 13 00 00 00     JMP_FALSE    loc_0A13            ; Rel: +0x13
  0A04:  01 00 00 00 00     PUSH_INT     0
  0A09:  26 00 00 00 00     ASSIGN       test_ifdef_bug_and_end_local0
  0A0E:  19 1A 00 00 00     LINE_NUM     26                  ; Code Line 26
loc_0A13:
  0A13:  1F                 RET                              ; mark end of function
;Function test_ifdef_bug_and_end() End
; ------------------------------------------------------------

;Function test_ifdef_bug_or_end() Begin
  0A14:  01 0A 00 00 00     PUSH_INT     10
  0A19:  26 01 00 00 00     ASSIGN       test_ifdef_bug_or_end_local0
  0A1E:  19 20 00 00 00     LINE_NUM     32                  ; Code Line 32
  0A23:  19 21 00 00 00     LINE_NUM     33                  ; Code Line 33
  0A28:  24 01 00 00 00     PUSH_VAR     test_ifdef_bug_or_end_local0
  0A2D:  01 64 00 00 00     PUSH_INT     100
  0A32:  0F                 GT           
  0A33:  2D 05 00 00 00     OR_JMP       loc_0A39            ; Rel: +0x5
  0A38:  0E                 LOG_OR       
loc_0A39:
  0A39:  18 13 00 00 00     JMP_FALSE    loc_0A4D            ; Rel: +0x13
  0A3E:  01 00 00 00 00     PUSH_INT     0
  0A43:  26 01 00 00 00     ASSIGN       test_ifdef_bug_or_end_local0
  0A48:  19 29 00 00 00     LINE_NUM     41                  ; Code Line 41
loc_0A4D:
  0A4D:  1F                 RET                              ; mark end of function
;Function test_ifdef_bug_or_end() End
; ------------------------------------------------------------

;Function test_ifdef_bug_or_start() Begin
  0A4E:  01 64 00 00 00     PUSH_INT     100
  0A53:  26 02 00 00 00     ASSIGN       test_ifdef_bug_or_start_local0
  0A58:  19 2F 00 00 00     LINE_NUM     47                  ; Code Line 47
  0A5D:  19 30 00 00 00     LINE_NUM     48                  ; Code Line 48
  0A62:  24 02 00 00 00     PUSH_VAR     test_ifdef_bug_or_start_local0
  0A67:  01 32 00 00 00     PUSH_INT     50
  0A6C:  0F                 GT           
  0A6D:  18 13 00 00 00     JMP_FALSE    loc_0A81            ; Rel: +0x13
  0A72:  01 32 00 00 00     PUSH_INT     50
  0A77:  26 02 00 00 00     ASSIGN       test_ifdef_bug_or_start_local0
  0A7C:  19 39 00 00 00     LINE_NUM     57                  ; Code Line 57
loc_0A81:
  0A81:  1F                 RET                              ; mark end of function
;Function test_ifdef_bug_or_start() End
; ------------------------------------------------------------

;Function test_ifdef_bug_and_start() Begin
  0A82:  01 64 00 00 00     PUSH_INT     100
  0A87:  26 03 00 00 00     ASSIGN       test_ifdef_bug_and_start_local0
  0A8C:  19 40 00 00 00     LINE_NUM     64                  ; Code Line 64
  0A91:  19 41 00 00 00     LINE_NUM     65                  ; Code Line 65
  0A96:  24 03 00 00 00     PUSH_VAR     test_ifdef_bug_and_start_local0
  0A9B:  01 32 00 00 00     PUSH_INT     50
  0AA0:  0F                 GT           
  0AA1:  18 13 00 00 00     JMP_FALSE    loc_0AB5            ; Rel: +0x13
  0AA6:  01 32 00 00 00     PUSH_INT     50
  0AAB:  26 03 00 00 00     ASSIGN       test_ifdef_bug_and_start_local0
  0AB0:  19 4A 00 00 00     LINE_NUM     74                  ; Code Line 74
loc_0AB5:
  0AB5:  1F                 RET                              ; mark end of function
;Function test_ifdef_bug_and_start() End
; ------------------------------------------------------------

;Function test_ifdef_bug_complex() Begin
  0AB6:  01 01 00 00 00     PUSH_INT     1
  0ABB:  26 04 00 00 00     ASSIGN       test_ifdef_bug_complex_local0
  0AC0:  19 51 00 00 00     LINE_NUM     81                  ; Code Line 81
  0AC5:  19 52 00 00 00     LINE_NUM     82                  ; Code Line 82
  0ACA:  01 02 00 00 00     PUSH_INT     2
  0ACF:  26 05 00 00 00     ASSIGN       test_ifdef_bug_complex_local1
  0AD4:  19 52 00 00 00     LINE_NUM     82                  ; Code Line 82
  0AD9:  19 53 00 00 00     LINE_NUM     83                  ; Code Line 83
  0ADE:  24 04 00 00 00     PUSH_VAR     test_ifdef_bug_complex_local0
  0AE3:  01 01 00 00 00     PUSH_INT     1
  0AE8:  0D                 EQ           
  0AE9:  2D 10 00 00 00     OR_JMP       loc_0AFA            ; Rel: +0x10
  0AEE:  24 05 00 00 00     PUSH_VAR     test_ifdef_bug_complex_local1
  0AF3:  01 02 00 00 00     PUSH_INT     2
  0AF8:  0D                 EQ           
  0AF9:  0E                 LOG_OR       
loc_0AFA:
  0AFA:  2C 05 00 00 00     AND_JMP      loc_0B00            ; Rel: +0x5
  0AFF:  15                 LOG_AND      
loc_0B00:
  0B00:  18 13 00 00 00     JMP_FALSE    loc_0B14            ; Rel: +0x13
  0B05:  01 00 00 00 00     PUSH_INT     0
  0B0A:  26 04 00 00 00     ASSIGN       test_ifdef_bug_complex_local0
  0B0F:  19 5B 00 00 00     LINE_NUM     91                  ; Code Line 91
loc_0B14:
  0B14:  1F                 RET                              ; mark end of function
;Function test_ifdef_bug_complex() End
; ------------------------------------------------------------

;Function test_ifdef_double_dangling() Begin
  0B15:  01 01 00 00 00     PUSH_INT     1
  0B1A:  26 06 00 00 00     ASSIGN       test_ifdef_double_dangling_local0
  0B1F:  19 62 00 00 00     LINE_NUM     98                  ; Code Line 98
  0B24:  19 63 00 00 00     LINE_NUM     99                  ; Code Line 99
  0B29:  24 06 00 00 00     PUSH_VAR     test_ifdef_double_dangling_local0
  0B2E:  01 00 00 00 00     PUSH_INT     0
  0B33:  0F                 GT           
  0B34:  2C 05 00 00 00     AND_JMP      loc_0B3A            ; Rel: +0x5
  0B39:  15                 LOG_AND      
loc_0B3A:
  0B3A:  2D 05 00 00 00     OR_JMP       loc_0B40            ; Rel: +0x5
  0B3F:  0E                 LOG_OR       
loc_0B40:
  0B40:  18 13 00 00 00     JMP_FALSE    loc_0B54            ; Rel: +0x13
  0B45:  01 00 00 00 00     PUSH_INT     0
  0B4A:  26 06 00 00 00     ASSIGN       test_ifdef_double_dangling_local0
  0B4F:  19 6F 00 00 00     LINE_NUM     111                 ; Code Line 111
loc_0B54:
  0B54:  1F                 RET                              ; mark end of function
;Function test_ifdef_double_dangling() End
; ------------------------------------------------------------

;Function getImplantPrice() Begin
  0B55:  01 7B 00 00 00     PUSH_INT     123
  0B5A:  1F                 RET          
  0B5B:  19 74 00 00 00     LINE_NUM     116                 ; Code Line 116
  0B60:  1F                 RET                              ; mark end of function
;Function getImplantPrice() End
; ------------------------------------------------------------

;Function test_ifdef_func_arg() Begin
  0B61:  01 01 00 00 00     PUSH_INT     1
  0B66:  26 08 00 00 00     ASSIGN       test_ifdef_func_arg_local0
  0B6B:  19 79 00 00 00     LINE_NUM     121                 ; Code Line 121
  0B70:  19 7A 00 00 00     LINE_NUM     122                 ; Code Line 122
  0B75:  24 08 00 00 00     PUSH_VAR     test_ifdef_func_arg_local0
  0B7A:  2C 05 00 00 00     AND_JMP      loc_0B80            ; Rel: +0x5
  0B7F:  15                 LOG_AND      
loc_0B80:
  0B80:  26 07 00 00 00     ASSIGN       getImplantPrice_arg0
  0B85:  1A                 ARG_COMMIT   
  0B86:  1E 06 00 00 00     CALL_FUNC    getImplantPrice
  0B8B:  01 00 00 00 00     PUSH_INT     0
  0B90:  0F                 GT           
  0B91:  18 13 00 00 00     JMP_FALSE    loc_0BA5            ; Rel: +0x13
  0B96:  01 00 00 00 00     PUSH_INT     0
  0B9B:  26 08 00 00 00     ASSIGN       test_ifdef_func_arg_local0
  0BA0:  19 83 00 00 00     LINE_NUM     131                 ; Code Line 131
loc_0BA5:
  0BA5:  1F                 RET                              ; mark end of function
;Function test_ifdef_func_arg() End
; ------------------------------------------------------------
