"""
generate_LGC/lgc_generator.py
整个 LGC 反编译生成的核心类，负责调度 Parser、CFG、AST、FlowStructurer 和 Optimizer。
"""

import os
from logger import logger

from generate_LGC.asm_parser import AsmParser
from generate_LGC.cfg_builder import CFGBuilder
from generate_LGC.ast_builder import ASTBuilder
from generate_LGC.flow_structurer import FlowStructurer
from generate_LGC.lgc_context import LgcContext
from generate_LGC.lgc_optimizer import LgcOptimizer


class LgcGenerator:
    """
    LGC 源码生成器类。
    """

    @staticmethod
    def generate_complete_lgc(input_asm: str, output_lgc: str, extern_csv: str) -> None:
        """
        生成完整的 LGC 伪代码文件的主方法。

        :param input_asm: 中间生成的 ASM 汇编文件路径
        :param output_lgc: 最终输出的 LGC 文件路径
        :param extern_csv: 包含变量映射和类型的 CSV 文件路径
        """
        if not os.path.exists(input_asm):
            logger.error(f"[LGC-GENERATOR] Error: Input ASM file '{input_asm}' not found.")
            return

        # 1. 实例化上下文并加载 CSV (增强的解析与容错)
        context = LgcContext()
        context.load_from_csv(extern_csv)

        # 2. 准备反编译解析工具
        parser = AsmParser()
        cfg_builder = CFGBuilder()

        logger.info(f"[LGC-GENERATOR] Reading '{input_asm}' for Complete LGC Generation...")
        methods = parser.parse_file(input_asm)

        # 3. 开始向目标文件写入代码
        with open(output_lgc, 'w', encoding='utf-8') as out_f:
            # 写入文件头注释
            out_f.write("// ==========================================\n")
            out_f.write("// Generated by LGC Decompiler V 0.1.0\n")
            out_f.write(f"// Decompiled LGC Source File\n")
            out_f.write(f"// Original ASM: {input_asm}\n")
            out_f.write("// ==========================================\n\n")

            # 通过上下文中的 Header Manager 写入全局变量和 Extern 声明
            out_f.write(context.header_manager.build_header_string())

            out_f.write("\n// ==========================================\n")
            out_f.write("// Function Implementations\n")
            out_f.write("// ==========================================\n\n")

            # 4. 遍历每个汇编方法进行反编译
            for method in methods:
                logger.info(f"[LGC-GENERATOR]  -> Decompiling {method.name}...")

                # 4.1 构建控制流图 (CFG)
                blocks = cfg_builder.build_cfg(method)

                # 4.2 准备抽象语法树 (AST) 转换器
                ast_builder = ASTBuilder(ext_def_map=context.ext_map, func_def_map=context.func_map)

                for i, block in enumerate(blocks):
                    is_last = (i == len(blocks) - 1)
                    try:
                        # 生成基本块内的 AST 语句
                        block.statements = ast_builder.build_block_ast(
                            block, is_last_physical_block=is_last, method_name=method.name
                        )
                    except Exception as e:
                        block.statements = []
                        logger.error(f"    [LGC-GENERATOR] AST Error in block {block.id} of {method.name}: {e}")

                # 4.3 折叠控制流结构 (If, While 等)
                structurer = FlowStructurer(blocks)
                structurer.build_structure()
                raw_pseudo_code = structurer.fold_into_tree().to_code(indent=1)

                # 4.4 调用优化器清理双分号与无意义的占位返回
                pseudo_code = LgcOptimizer.optimize(raw_pseudo_code, method.name)

                # 4.5 写入函数签名（包含从 Context 中获取的带默认值的参数）
                params = context.func_params.get(method.name, [])
                out_f.write(f"{method.name}({', '.join(params)})\n{{\n")

                # 4.6 写入当前函数的局部变量（包含静态初始化数组等）
                locals_list = context.func_locals.get(method.name, [])
                if locals_list:
                    for loc_decl in locals_list:
                        out_f.write(f"    {loc_decl}\n")
                    out_f.write("\n")

                # 4.7 写入反编译后清洗过的核心逻辑体
                if pseudo_code.strip():
                    out_f.write(pseudo_code + "\n")

                out_f.write("}\n\n")

        logger.info(f"[LGC-GENERATOR] Success! Complete LGC source written to '{output_lgc}'\n")