"""
generate_intermediate/renderer_asm.py
Generates a human-readable Assembly (ASM) dump.
Style: Function-Bucket Based with Intelligent Boundary Correction.
Fix: Recursively shifts RETs and LINE_NUMs to the previous function based on "Impossible Sequences".
Update: Added specific handling for Empty Functions (Double RET split).
"""

import os
from typing import List, Dict, Set, Optional, Tuple
from collections import defaultdict
from logger import logger
from core.context import LgdAnalysisContext
from common.structures import BytecodeEntry
from common.opcodes import LgdOpcodes
from common.definitions import LgdDefinitions

class LgdAsmRenderer:
    def __init__(self, context: LgdAnalysisContext):
        self.ctx = context
        self.p1_var_map: Dict[int, str] = {}
        self.global_func_map: Dict[int, str] = {}
        self.extern_id_map: Dict[int, str] = {}
        self.p1_owner_map: Dict[int, str] = {}
        self.func_ranges: List[Tuple[int, int, str]] = []
        self.jump_targets: Set[int] = set()
        self.HEX_COLUMN_WIDTH = 18

    def render(self, output_path: str):
        self._build_maps()
        self._analyze_jump_targets()

        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                # --- Header ---
                f.write("; ===========================================================================\n")
                f.write(f"; File: {os.path.basename(self.ctx.file_path)}\n")
                f.write("; Generated by LGD Decompiler V_0.1.0\n")
                f.write(f"; Bytecode Start: 0x{self.ctx.bytecode_offset_start + 4:X}\n")
                f.write("; Format: [File Offset] [Hex Dump]           [Mnemonic]     [Operands]     [Comments]\n")
                f.write("; ===========================================================================\n")

                # 1. Bucket Instructions
                func_bucket: Dict[str, List[BytecodeEntry]] = defaultdict(list)
                orphan_instrs: List[BytecodeEntry] = []
                sorted_instrs = sorted(self.ctx.bytecode_instructions, key=lambda x: x.offset)

                for entry in sorted_instrs:
                    owner_name = self._get_instruction_owner(entry.offset)
                    if owner_name:
                        func_bucket[owner_name].append(entry)
                    else:
                        orphan_instrs.append(entry)

                # ========================================================
                # 2. Boundary Refinement (Intelligent Correction for empty func)
                # ========================================================
                sorted_func_names = [r[2] for r in self.func_ranges]


                # for i in range(len(sorted_func_names) - 1):
                # fix again foe empty func
                # now use in reverse order
                for i in range(len(sorted_func_names) - 2, -1, -1):
                    curr_name = sorted_func_names[i]
                    next_name = sorted_func_names[i+1]

                    curr_list = func_bucket[curr_name]
                    next_list = func_bucket[next_name]

                    # Loop to continuously check the start of next_list
                    while next_list:
                        first_op = next_list[0]
                        should_move = False
                        items_to_move = 0

                        # --- Case A: Starts with RET ---
                        if first_op.opcode == 0x1F: # RET
                            # If there are MORE instructions after this RET, this RET definitely belongs to Prev.
                            if len(next_list) > 1:
                                should_move = True
                                items_to_move = 1
                            else:
                                # This is the ONLY instruction left in Next.
                                # Only steal it if Curr DOES NOT end with RET.
                                curr_has_ret = (curr_list and curr_list[-1].opcode == 0x1F)
                                if not curr_has_ret:
                                    should_move = True
                                    items_to_move = 1

                        # --- Case B: Starts with LINE_NUM followed by RET ---
                        elif first_op.mnemonic == "LINE_NUM":
                            if len(next_list) > 1 and next_list[1].opcode == 0x1F:
                                # Found [LINE_NUM, RET, ...] sequence at start.
                                # This block belongs to Prev.
                                should_move = True
                                items_to_move = 2

                        # Execute Move
                        if should_move:
                            for _ in range(items_to_move):
                                curr_list.append(next_list.pop(0))
                        else:
                            # If we didn't move anything, stop checking this pair
                            break

                # ========================================================
                # 2.5. Empty Function Boundary Fix (Double RET Split)
                # ========================================================
                # Run a secondary pass to detect empty functions (Func B) appearing as [RET, RET]
                # resulting from Func A missing its RET.
                self._fix_empty_function_boundaries(func_bucket, sorted_func_names)

                # ========================================================
                # 3. Render
                # ========================================================
                if orphan_instrs:
                    f.write("\n; --- Orphan / Global Instructions ---\n")
                    for entry in orphan_instrs:
                        lines = self._format_instruction(entry)
                        for line in lines: f.write(line + "\n")
                    f.write(f"; {'-' * 60}\n")

                for start, end, func_name in self.func_ranges:
                    f.write(f"\n;Function {func_name}() Begin\n")

                    my_instrs = func_bucket.get(func_name, [])

                    for i, entry in enumerate(my_instrs):
                        extra_comment = ""
                        # Mark RET if it is the absolute last instruction
                        if entry.opcode == 0x1F:
                            is_last = (i == len(my_instrs) - 1)
                            if is_last:
                                extra_comment = "mark end of function"

                        lines = self._format_instruction(entry, extra_comment)
                        for line in lines:
                            f.write(line + "\n")

                    f.write(f";Function {func_name}() End\n")
                    f.write(f"; {'-' * 60}\n")

            logger.info(f"[AsmRenderer] Assembly dumped to: {output_path}")

        except Exception as e:
            logger.error(f"[AsmRenderer] Failed to write ASM: {e}")
            import traceback
            traceback.print_exc()

    def _fix_empty_function_boundaries(self, func_bucket: Dict[str, List[BytecodeEntry]], sorted_func_names: List[str]):
        """
        Scans for functions that appear to start with consecutive RETs.
        This usually indicates that the previous function missed its RET, and the
        next function is an empty function (containing only one RET).
        Logic: If Next starts with [RET, RET], move the first RET to Curr.
        """
        for i in range(len(sorted_func_names) - 1):
            curr_name = sorted_func_names[i]
            next_name = sorted_func_names[i+1]

            curr_list = func_bucket[curr_name]
            next_list = func_bucket[next_name]

            # We need at least 2 instructions in next_list to detect [RET, RET]
            if len(next_list) >= 2:
                op0 = next_list[0]
                op1 = next_list[1]

                # Opcode 0x1F is RET
                if op0.opcode == 0x1F and op1.opcode == 0x1F:
                    logger.warning(
                        f"[AsmRenderer] Empty Function boundary detected at '{next_name}'. "
                        f"Found [RET, RET] sequence. Moving first RET to '{curr_name}'."
                    )

                    # Move the first RET from next to curr
                    moved_ret = next_list.pop(0)
                    curr_list.append(moved_ret)

    def _get_instruction_owner(self, offset: int) -> Optional[str]:
        for start, end, name in self.func_ranges:
            if start <= offset < end:
                return name
            if start > offset:
                break
        return None

    def _build_maps(self):
        logger.debug("[AsmRenderer] Building Symbol Maps & Ranges...")
        bytecode_base = self.ctx.bytecode_offset_start
        all_symbols = self.ctx.symbol_table
        sorted_symbols_p1 = sorted(all_symbols, key=lambda s: s.p1_idx)

        # 1. Build P1/Extern Maps
        total_p1_count = len(self.ctx.literal_table)
        for i, sym in enumerate(sorted_symbols_p1):
            base_name = sym.name if sym.name else f"UnkSym_{i}"
            base_type = sym.type_val & 0xFF
            is_function = (base_type == LgdDefinitions.BASE_FUNCTION)
            is_extern = (base_type == LgdDefinitions.BASE_EXTERN)

            self.p1_owner_map[sym.p1_idx] = base_name
            if is_extern: self.extern_id_map[sym.meta] = base_name

            start_idx = sym.p1_idx
            end_idx = sorted_symbols_p1[i+1].p1_idx if i + 1 < len(sorted_symbols_p1) else total_p1_count

            for p1_idx in range(start_idx, end_idx):
                offset_in_group = p1_idx - start_idx
                if is_function:
                    if offset_in_group < sym.size: name = f"{base_name}_arg{offset_in_group}"
                    else:
                        local_idx = offset_in_group - sym.size
                        name = f"{base_name}_local{local_idx}"
                    self.p1_var_map[p1_idx] = name
                elif is_extern:
                    self.p1_var_map[p1_idx] = f"{base_name}_arg{offset_in_group}"
                else:
                    self.p1_var_map[p1_idx] = base_name if p1_idx == start_idx else f"{base_name}_{offset_in_group}"

        # Global IDs
        for idx, entry in enumerate(self.ctx.literal_table):
            if entry.is_group_head and idx in self.p1_owner_map:
                gid = entry.global_id
                if gid != -1: self.global_func_map[gid] = self.p1_owner_map[idx]
            if idx not in self.p1_var_map: self.p1_var_map[idx] = f"var_{idx}"

        # 2. Build Function Ranges
        func_starts = []
        for sym in all_symbols:
            if (sym.type_val & 0xFF) == LgdDefinitions.BASE_FUNCTION:
                abs_start = bytecode_base + sym.meta
                name = sym.name if sym.name else f"Func_{sym.p1_idx}"
                func_starts.append((abs_start, name))

        func_starts.sort(key=lambda x: x[0])

        if self.ctx.bytecode_instructions:
            last_instr = sorted(self.ctx.bytecode_instructions, key=lambda x: x.offset)[-1]
            bytecode_end_abs = last_instr.offset + len(last_instr.raw_bytes) + 100
        else:
            bytecode_end_abs = bytecode_base + 999999

        for i in range(len(func_starts)):
            start_off, name = func_starts[i]
            end_off = func_starts[i+1][0] if i + 1 < len(func_starts) else bytecode_end_abs
            self.func_ranges.append((start_off, end_off, name))

    def _analyze_jump_targets(self):
        JUMP_OPCODES = {0x18, 0x1C, 0x2C, 0x2D}
        AWAIT = {0X1B}
        IFF = {0X1D}

        for entry in self.ctx.bytecode_instructions:
            if entry.opcode in JUMP_OPCODES:
                if entry.operands and isinstance(entry.operands[0], int):
                    # there is a error, it should be calculated as offset + 1 (fixed opcode length) +operands
                    # target_abs = entry.offset + len(entry.raw_bytes) + entry.operands[0]
                    target_abs = entry.offset + 1 + entry.operands[0]
                    self.jump_targets.add(target_abs)

            # updated await algorithm (start +offset)
            elif entry.opcode in AWAIT:
                if entry.operands and isinstance(entry.operands[0], int):
                    target_abs = self.ctx.bytecode_offset_start + 4 + entry.operands[0]
                    self.jump_targets.add(target_abs)
            # also fix IFF the second operand is also calculated as  (start +offset)
            elif entry.opcode in IFF:
                if len(entry.operands) > 0 and isinstance(entry.operands[0], int):
                    target_abs_1 = entry.offset + 1 + entry.operands[0]
                    self.jump_targets.add(target_abs_1)
                if len(entry.operands) > 1 and isinstance(entry.operands[1], int):
                    target_abs = self.ctx.bytecode_offset_start + 4 + entry.operands[1]
                    self.jump_targets.add(target_abs)

    def _format_instruction(self, entry: BytecodeEntry, extra_comment: str = "") -> List[str]:
        output_lines = []
        if entry.offset in self.jump_targets:
            output_lines.append(f"loc_{entry.offset:04X}:")

        raw_hex = [f"{b:02X}" for b in entry.raw_bytes]
        hex_capacity = self.HEX_COLUMN_WIDTH // 3
        hex_main = " ".join(raw_hex[:hex_capacity])
        hex_rem = raw_hex[hex_capacity:]

        op_str = self._resolve_operands(entry)

        comment = ""
        if LgdOpcodes.MIN_EXT_OPCODE <= entry.opcode <= LgdOpcodes.MAX_EXT_OPCODE:
            if entry.opcode in self.extern_id_map: comment = f"; {self.extern_id_map[entry.opcode]}"

        if entry.opcode == 0x1D: comment = "; Iff Jump"
        elif entry.mnemonic == "LINE_NUM" and entry.operands: comment = f"; Code Line {entry.operands[0]}"
        elif entry.opcode in {0x18, 0x1C, 0x2C, 0x2D} and entry.operands:
             if isinstance(entry.operands[0], int):
                sign = "+" if entry.operands[0] >= 0 else ""
                comment = f"; Rel: {sign}0x{entry.operands[0]:X}"

        if extra_comment: comment += f" ({extra_comment})" if comment else f"; {extra_comment}"

        line = f"  {entry.offset:04X}:  {hex_main:<{self.HEX_COLUMN_WIDTH}} {entry.mnemonic:<12} {op_str}"
        if comment: line = f"{line:<60} {comment}" if len(line) < 60 else f"{line}  {comment}"
        output_lines.append(line)

        while hex_rem:
            chunk = hex_rem[:hex_capacity]
            hex_rem = hex_rem[hex_capacity:]
            output_lines.append(f"{' '*8}{' '.join(chunk)}")

        return output_lines

    def _resolve_operands(self, entry: BytecodeEntry) -> str:
        if not entry.operands: return ""
        parts = []
        VAR_OPS = {0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27}
        FUNC_OPS = {0x1E}
        JUMP_OPS = {0x18, 0x1C, 0x2C, 0x2D}
        AWAIT = {0X1B}
        IFF = {0X1D}

        for idx, op in enumerate(entry.operands):
            val_str = str(op)
            if isinstance(op, str):
                safe_str = op.replace('\n', '\\n').replace('\r', '\\r')
                if len(safe_str) > 40: safe_str = safe_str[:37] + "..."
                val_str = f'"{safe_str}"'
            elif isinstance(op, int):
                if entry.opcode in VAR_OPS:
                    if entry.opcode == 0x27 and idx == 1: val_str = LgdOpcodes.ASSIGN_OP_MAP.get(op, f"OP_{op:02X}")
                    else: val_str = self.p1_var_map.get(op, f"var_{op}")

                elif entry.opcode in FUNC_OPS: val_str = self.global_func_map.get(op, f"Func_{op}")

                # add for await
                elif entry.opcode in AWAIT and idx == 0:
                    target_abs = self.ctx.bytecode_offset_start + 4 + op
                    val_str = f"loc_{target_abs:04X}"

                elif entry.opcode in IFF and idx == 0:
                     target_abs = entry.offset + 1 + op
                     val_str = f"loc_{target_abs:04X}"

                elif entry.opcode in IFF and idx == 1:
                    target_abs = self.ctx.bytecode_offset_start + 4 + op
                    val_str = f"loc_{target_abs:04X}"

                elif entry.opcode in JUMP_OPS and idx == 0:
                     # also fix the jump algorithm +1
                     # target_abs = entry.offset + len(entry.raw_bytes) + op
                     target_abs = entry.offset + 1 + op
                     val_str = f"loc_{target_abs:04X}"

                else: val_str = f"0x{op:X}" if abs(op) > 9 else str(op)
            parts.append(val_str)
        return ", ".join(parts)